spring.application.name=mail-clone

# ===== MONGODB ATLAS CONFIG =====
spring.data.mongodb.uri=mongodb+srv://emailhog:Emailhog2025@emailhog-cluster.fojxtnm.mongodb.net/?appName=emailhog-cluster
spring.data.mongodb.database=emailhog

# ===== DISABLE H2 AND JPA ENTIRELY =====
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# ===== GEMINI AI CONFIG =====
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
gemini.api.key=AIzaSyCL1548pMF-ypyWGhqezxDV_re2K9sfKi8

# Multipart file upload config
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB